Fix script to handle invalid input properly

diff --git a/pistar-mmdvmhshatdowngrade b/pistar-mmdvmhshatdowngrade
--- a/pistar-mmdvmhshatdowngrade
+++ b/pistar-mmdvmhshatdowngrade
@@ -2,7 +2,7 @@
 #
 ###############################################################################
 #                                                                             #
-#                   Pi-Star Custom Firmware Update Tool                       #
+#                     Pi-Star Firmware Downgrade Tool                         #
 #                                                                             #
 #    Version 0.1, Code, Design and Development by Florian Wolters (DF2ET).    #
 #                     Idea by Stefan Espringal (DL1BH)                        #
@@ -64,7 +64,7 @@ fi
 
 if [ -z "$2" ] || [ $VERSION == "" ]
 then
-   echo "Please choose the version to flash from the following list of ${#VERSIONS[@]} items:"
+   echo "Please choose the version to flash from the following list of ${#VERSIONS[@]} items by entering the corresponding line number:"
    I=1
    for ITEM in "${VERSIONS[@]}"
    do
@@ -78,88 +78,84 @@ then
    if [ "$CHOICE" == "q" -o "$CHOICE" == "Q" ]; then
       echo "Aborted."
       exit 1
-   fi
-   if [ $CHOICE -lt 1 -o $CHOICE -gt ${#VERSIONS[@]} ]; then
-      echo "Invalid choice. Aborting ..."
+   elif [ $CHOICE -ge 1 -a $CHOICE -le ${#VERSIONS[@]} ]; then
+      echo "Your choice: ${CHOICE} (${VERSIONS[(($CHOICE - 1))]})"
       echo ""
+      VERSION="${VERSIONS[(($CHOICE - 1))]}"
+      #
+      # Download the correct firmware
+      #
+      case ${1} in
+         hs_hat)
+            # Flashing MMDVM_HS Hat Modem
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
+            echo "Flashing your ${1} modem to version ${VERSION}"
+            curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hshat.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
+            chmod +x /tmp/mmdvmhshatfirmware/flash.sh
+            cd  /tmp/mmdvmhshatfirmware
+            ./flash.sh
+            echo ""
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
+            shutdown -r now
+            exit 0
+         ;;
+         hs_hat-12mhz)
+            # Flashing MMDVM_HS Hat Modem with 12.288 MHz TCXO
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
+            echo "Flashing your ${1} modem to the ${VERSION} version"
+            curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hshat-12mhz.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
+            chmod +x /tmp/mmdvmhshatfirmware/flash.sh
+            cd  /tmp/mmdvmhshatfirmware
+            ./flash.sh
+            echo ""
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
+            shutdown -r now
+            exit 0
+         ;;
+         hs_dual_hat)
+            # Flashing MMDVM_HS_DUAL Modem
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
+            echo "Flashing your ${1} modem to the ${VERSION} version"
+            curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hsdualhat.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
+            chmod +x /tmp/mmdvmhshatfirmware/flash.sh
+            cd  /tmp/mmdvmhshatfirmware
+            ./flash.sh
+            echo ""
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
+            shutdown -r now
+            exit 0
+         ;;
+         hs_dual_hat-12mhz)
+            # Flashing MMDVM_HS_DUAL Modem with 12.288 MHz TCXO
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
+            echo "Flashing your ${1} modem to the ${VERSION} version"
+            curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hsdualhat-12mhz.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
+            chmod +x /tmp/mmdvmhshatfirmware/flash.sh
+            cd  /tmp/mmdvmhshatfirmware
+            ./flash.sh
+            echo ""
+            rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
+            read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
+            shutdown -r now
+            exit 0
+         ;;
+         *)
+            # Un-recognised modem choice
+            echo "Your Choice of ${1} modem is not supported by this update tool"
+            exit 1
+         ;;
+      esac
+   else
+      echo "Invalid choice. Aborting ..."
       exit 2
    fi
 
-   echo "Your choice: ${CHOICE} (${VERSIONS[(($CHOICE - 1))]})"
-   VERSION="${VERSIONS[(($CHOICE - 1))]}"
 fi
-
-#
-# Download the correct firmware
-#
-if [ "$1" ]
-then
-  case ${1} in
-  hs_hat)
-    # Flashing MMDVM_HS Hat Modem
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
-    echo "Flashing your ${1} modem to version ${VERSION}"
-    curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hshat.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
-    chmod +x /tmp/mmdvmhshatfirmware/flash.sh
-    cd  /tmp/mmdvmhshatfirmware
-    ./flash.sh
-    echo ""
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
-    shutdown -r now
-    exit 0
-  ;;
-  hs_hat-12mhz)
-    # Flashing MMDVM_HS Hat Modem with 12.288 MHz TCXO
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
-    echo "Flashing your ${1} modem to the ${VERSION} version"
-    curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hshat-12mhz.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
-    chmod +x /tmp/mmdvmhshatfirmware/flash.sh
-    cd  /tmp/mmdvmhshatfirmware
-    ./flash.sh
-    echo ""
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
-    shutdown -r now
-    exit 0
-  ;;
-  hs_dual_hat)
-    # Flashing MMDVM_HS_DUAL Modem
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
-    echo "Flashing your ${1} modem to the ${VERSION} version"
-    curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hsdualhat.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
-    chmod +x /tmp/mmdvmhshatfirmware/flash.sh
-    cd  /tmp/mmdvmhshatfirmware
-    ./flash.sh
-    echo ""
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
-    shutdown -r now
-    exit 0
-  ;;
-  hs_dual_hat-12mhz)
-    # Flashing MMDVM_HS_DUAL Modem with 12.288 MHz TCXO
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    mkdir /tmp/mmdvmhshatfirmware 2> /dev/null
-    echo "Flashing your ${1} modem to the ${VERSION} version"
-    curl -s -L https://github.com/juribeparada/MMDVM_HS/releases/${VERSION} | egrep -o '/juribeparada/MMDVM_HS/releases/download/v[0-9.]*/install_fw_hsdualhat-12mhz.sh' | wget --base=http://github.com/ -i - -O /tmp/mmdvmhshatfirmware/flash.sh
-    chmod +x /tmp/mmdvmhshatfirmware/flash.sh
-    cd  /tmp/mmdvmhshatfirmware
-    ./flash.sh
-    echo ""
-    rm -rf /tmp/mmdvmhshatfirmware 2> /dev/null
-    read -n 1 -s -r -p "Flashing your ${1} modem complete, press any key to reboot your Pi-Star System..."
-    shutdown -r now
-    exit 0
-  ;;
-  *)
-    # Un-recognised modem choice
-    echo "Your Choice of ${1} modem is not supported by this update tool"
-    exit 1
-  ;;
-  esac
-fi
-exit 0
+exit 2
