Update pistar-expand

diff --git a/pistar-expand b/pistar-expand
--- a/pistar-expand
+++ b/pistar-expand
@@ -14,52 +14,52 @@ if [ "$(id -u)" != "0" ]; then
   exit 1
 fi
 
-get_init_sys() {
-	if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
-		SYSTEMD=1
-	elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
-		SYSTEMD=0
-	else
-		echo "Error - Unrecognised init system"
-		return 1
-	fi
-	}
+# Remount read-write
+mount -o remount,rw /boot
+mount -o remount,rw /
 
-do_expand_rootfs() {
-	get_init_sys
-	if [ $SYSTEMD -eq 1 ]; then
-		ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
-	else
-		if ! [ -h /dev/root ]; then
-			echo "Error - dont know how to expand this filesystem"
-			return 0
-		fi
-		ROOT_PART=$(readlink /dev/root)
-	fi
+# Figure out if this is a systemd system
+if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
+	SYSTEMD=1
+elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
+	SYSTEMD=0
+else
+	echo "Error - Unrecognised init system"
+	return 1
+fi
 
-	PART_NUM=${ROOT_PART#mmcblk0p}
-	if [ "$PART_NUM" = "$ROOT_PART" ]; then
-		echo "$ROOT_PART is not an SD card. Don't know how to expand"
+# Expand the root partition
+if [ $SYSTEMD -eq 1 ]; then
+	ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
+else
+	if ! [ -h /dev/root ]; then
+		echo "Error - dont know how to expand this filesystem"
 		return 0
 	fi
+	ROOT_PART=$(readlink /dev/root)
+fi
 
+PART_NUM=${ROOT_PART#mmcblk0p}
+if [ "$PART_NUM" = "$ROOT_PART" ]; then
+	echo "$ROOT_PART is not an SD card. Don't know how to expand"
+	return 0
+fi
 	if [ "$PART_NUM" -ne 2 ]; then
-		echo "Your partition layout is not currently supported by this tool, or your root filesystem is already expanded."
-		return 0
-	fi
+	echo "Your partition layout is not currently supported by this tool, or your root filesystem is already expanded."
+	return 0
+fi
 
-	LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)
-	if [ $LAST_PART_NUM -ne $PART_NUM ]; then
-		echo "$ROOT_PART is not the last partition. Don't know how to expand"
-		return 0
-	fi
-
-	# Get the starting offset of the root partition
-	PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
-	[ "$PART_START" ] || return 1
-	# Return value will likely be error for fdisk as it fails to reload the
-	# partition table because the root fs is mounted
-	fdisk /dev/mmcblk0 <<EOF
+LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)
+if [ $LAST_PART_NUM -ne $PART_NUM ]; then
+	echo "$ROOT_PART is not the last partition. Don't know how to expand"
+	return 0
+fi
+# Get the starting offset of the root partition
+PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
+[ "$PART_START" ] || return 1
+# Return value will likely be error for fdisk as it fails to reload the
+# partition table because the root fs is mounted
+fdisk /dev/mmcblk0 <<EOF
 p
 d
 $PART_NUM
@@ -72,8 +72,8 @@ p
 w
 EOF
 
-	# now set up an init.d script
-	cat <<EOF > /etc/init.d/resize2fs_once &&
+# now set up an init.d script
+cat <<EOF > /etc/init.d/resize2fs_once &&
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          resize2fs_once
@@ -103,19 +103,8 @@ case "\$1" in
     ;;
 esac
 EOF
-	chmod +x /etc/init.d/resize2fs_once &&
-	update-rc.d resize2fs_once defaults &&
-	}
-
-# Make the disks RW
-mount -o remount,rw /boot
-mount -o remount,rw /
-
-# Check if this is a Systemd based OS (It should be)
-get_init_sys
-
-# Expand the partition and create the boot service to expand the filesystem
-do_expand_rootfs
+chmod +x /etc/init.d/resize2fs_once &&
+update-rc.d resize2fs_once defaults &&
 
 # Remount read-only
 mount -o remount,ro /boot
